In [5]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [7]:
import os

# đổi đường dẫn tới đúng folder của bạn
os.chdir('/content/drive/MyDrive/Python_assignment/pandas')

# kiểm tra xem có file không
print(os.getcwd())
!ls

/content/drive/MyDrive/Python_assignment/numpy
students.csv  students.json  students.txt  students.xlsx  Untitled0.ipynb


In [14]:
path = "/content/drive/MyDrive/Python_assignment/pandas/students.csv"
df = pd.read_csv(path)
df.head()

id       name  age  math_score    city
0   1  Student_1   18          60   Hanoi
1   2  Student_2   19          62     HCM
2   3  Student_3   20          64  Danang
3   4  Student_4   21          66  Cantho
4   5  Student_5   22          68   Hanoi

Chủ đề 1 – Đọc file CSV, TXT, JSON, XLSX

Ví dụ 1: Đọc CSV & XLSX

In [11]:
import pandas as pd

df_csv = pd.read_csv("students.csv")
df_xlsx = pd.read_excel("students.xlsx")

print("CSV:")
print(df_csv.head())

print("\nXLSX:")
print(df_xlsx.head())


CSV:
   id       name  age  math_score    city
0   1  Student_1   18          60   Hanoi
1   2  Student_2   19          62     HCM
2   3  Student_3   20          64  Danang
3   4  Student_4   21          66  Cantho
4   5  Student_5   22          68   Hanoi

XLSX:
   id       name  age  math_score    city
0   1  Student_1   18          60   Hanoi
1   2  Student_2   19          62     HCM
2   3  Student_3   20          64  Danang
3   4  Student_4   21          66  Cantho
4   5  Student_5   22          68   Hanoi


Ví dụ 2: Đọc TXT (tab) & JSON

In [12]:
df_txt = pd.read_csv("students.txt", sep="\t")
df_json = pd.read_json("students.json")

print("TXT (tab):")
print(df_txt.head())

print("\nJSON:")
print(df_json.head())



TXT (tab):
   id       name  age  math_score    city
0   1  Student_1   18          60   Hanoi
1   2  Student_2   19          62     HCM
2   3  Student_3   20          64  Danang
3   4  Student_4   21          66  Cantho
4   5  Student_5   22          68   Hanoi

JSON:
   id       name  age  math_score    city
0   1  Student_1   18          60   Hanoi
1   2  Student_2   19          62     HCM
2   3  Student_3   20          64  Danang
3   4  Student_4   21          66  Cantho
4   5  Student_5   22          68   Hanoi


Chủ đề 2 – Ghi file CSV, TXT, JSON, XLSX

Ví dụ 1: Ghi sang CSV và TXT

In [15]:
df_txt.to_csv("out_students.csv", index=False)          # bỏ cột index
df_txt.to_csv("out_students.txt", index=False, sep="\t")


Ví dụ 2: Ghi sang JSON và XLSX

In [16]:
df.to_json("out_students.json", orient="records", indent=2, force_ascii=False)
df.to_excel("out_students.xlsx", index=False)


Chủ đề 3 – Chọn cột, lọc dòng cơ bản

Ví dụ 1: Chọn một vài cột

In [17]:
cols = ["id", "name", "math_score"]
df_small = df[cols]
df_small.head()


id       name  math_score
0   1  Student_1          60
1   2  Student_2          62
2   3  Student_3          64
3   4  Student_4          66
4   5  Student_5          68

Ví dụ 2: Lọc theo điều kiện

In [25]:
# Học sinh có điểm toán > 80
# Học sinh ở HCM

hcm_students = df[(df["city"] == "HCM") & (df["math_score"] > 80)]
hcm_students.head()

id        name  age  math_score city
13  14  Student_14   21          86  HCM
17  18  Student_18   20          94  HCM

Chủ đề 4 – Thêm cột mới

Ví dụ 1: Thêm cột đánh giá (Pass/Fail)

In [26]:
df["result"] = df["math_score"].apply(lambda x: "Pass" if x >= 75 else "Fail")
df.head()

id       name  age  math_score    city result
0   1  Student_1   18          60   Hanoi   Fail
1   2  Student_2   19          62     HCM   Fail
2   3  Student_3   20          64  Danang   Fail
3   4  Student_4   21          66  Cantho   Fail
4   5  Student_5   22          68   Hanoi   Fail

Ví dụ 2: Thêm cột nhóm tuổi

In [27]:
def age_group(age):
    if age <= 19:
        return "Teen"
    elif age <= 21:
        return "Young"
    return "Adult"

df["age_group"] = df["age"].apply(age_group)
df.head()


id       name  age  math_score    city result age_group
0   1  Student_1   18          60   Hanoi   Fail      Teen
1   2  Student_2   19          62     HCM   Fail      Teen
2   3  Student_3   20          64  Danang   Fail     Young
3   4  Student_4   21          66  Cantho   Fail     Young
4   5  Student_5   22          68   Hanoi   Fail     Adult

Chủ đề 5 – Sort (sắp xếp dữ liệu)

Ví dụ 1: Sắp xếp theo điểm toán giảm dần

In [28]:
df_sorted_score = df.sort_values(by="math_score", ascending=False)
df_sorted_score.head()

id        name  age  math_score    city result age_group
19  20  Student_20   22          98  Cantho   Pass     Adult
18  19  Student_19   21          96  Danang   Pass     Young
17  18  Student_18   20          94     HCM   Pass     Young
16  17  Student_17   19          92   Hanoi   Pass      Teen
15  16  Student_16   18          90  Cantho   Pass      Teen

Ví dụ 2: Sắp xếp theo city rồi đến age

In [29]:
df_sorted_multi = df.sort_values(by=["city", "age"], ascending=[True, True])
df_sorted_multi.head()


id        name  age  math_score    city result age_group
15  16  Student_16   18          90  Cantho   Pass      Teen
11  12  Student_12   19          82  Cantho   Pass      Teen
7    8   Student_8   20          74  Cantho   Fail     Young
3    4   Student_4   21          66  Cantho   Fail     Young
19  20  Student_20   22          98  Cantho   Pass     Adult

Chủ đề 6 – Groupby (thống kê theo nhóm)

Ví dụ 1: Điểm toán trung bình theo thành phố

In [30]:
avg_by_city = df.groupby("city")["math_score"].mean()
print(avg_by_city)


city
Cantho    82.0
Danang    80.0
HCM       78.0
Hanoi     76.0
Name: math_score, dtype: float64


Ví dụ 2: Đếm số học sinh theo city và nhóm tuổi

In [31]:
count_by_city_age = df.groupby(["city", "age_group"])["id"].count()
print(count_by_city_age)


city    age_group
Cantho  Adult        1
        Teen         2
        Young        2
Danang  Adult        1
        Teen         2
        Young        2
HCM     Adult        1
        Teen         2
        Young        2
Hanoi   Adult        1
        Teen         2
        Young        2
Name: id, dtype: int64


Chủ đề 7 – Xử lý missing values (NaN)

Đầu tiên tạo ví dụ có NaN:

In [32]:
df_nan = df.copy()
df_nan.loc[0, "math_score"] = None
df_nan.loc[3, "city"] = None


Ví dụ 1: Kiểm tra NaN

In [33]:
print(df_nan.isna().sum())   # xem mỗi cột có bao nhiêu NaN


id            0
name          0
age           0
math_score    1
city          1
result        0
age_group     0
dtype: int64


Ví dụ 2: Điền giá trị thay thế

In [38]:
# Điền điểm bị thiếu bằng điểm trung bình
df_nan["math_score"] = df_nan["math_score"].fillna(df_nan["math_score"].mean())

# Điền city bị thiếu bằng "Unknown"
df_nan["city"] = df_nan["city"].fillna("Unknown")
df_nan.pad()

/tmp/ipython-input-2586645260.py:6: FutureWarning: DataFrame.pad/Series.pad is deprecated. Use DataFrame.ffill/Series.ffill instead
  df_nan.pad()


id        name  age  math_score     city result age_group
0    1   Student_1   18        80.0    Hanoi   Fail      Teen
1    2   Student_2   19        62.0      HCM   Fail      Teen
2    3   Student_3   20        64.0   Danang   Fail     Young
3    4   Student_4   21        66.0  Unknown   Fail     Young
4    5   Student_5   22        68.0    Hanoi   Fail     Adult
5    6   Student_6   18        70.0      HCM   Fail      Teen
6    7   Student_7   19        72.0   Danang   Fail      Teen
7    8   Student_8   20        74.0   Cantho   Fail     Young
8    9   Student_9   21        76.0    Hanoi   Pass     Young
9   10  Student_10   22        78.0      HCM   Pass     Adult
10  11  Student_11   18        80.0   Danang   Pass      Teen
11  12  Student_12   19        82.0   Cantho   Pass      Teen
12  13  Student_13   20        84.0    Hanoi   Pass     Young
13  14  Student_14   21        86.0      HCM   Pass     Young
14  15  Student_15   22        88.0   Danang   Pass     Adult
15  16  Student_16   18        90.0   Cantho   Pass      Teen
16  17  Student_17   19        92.0    Hanoi   Pass      Teen
17  18  Student_18   20        94.0      HCM   Pass     Young
18  19  Student_19   21        96.0   Danang   Pass     Young
19  20  Student_20   22        98.0   Cantho   Pass     Adult

Chủ đề 8 – Lọc nâng cao với nhiều điều kiện

Ví dụ 1: AND ( & )

In [40]:
# Học sinh ở HCM và điểm toán > 80
cond = (df["city"] == "HCM") & (df["math_score"] > 80)
df_hcm_high = df[cond]
df_hcm_high.head()

id        name  age  math_score city result age_group
13  14  Student_14   21          86  HCM   Pass     Young
17  18  Student_18   20          94  HCM   Pass     Young

Ví dụ 2: OR ( | )

In [41]:
# Ở Hanoi hoặc điểm toán >= 90
cond2 = (df["city"] == "Hanoi") | (df["math_score"] >= 90)
df_filtered = df[cond2]
df_filtered.head()

id        name  age  math_score    city result age_group
0    1   Student_1   18          60   Hanoi   Fail      Teen
4    5   Student_5   22          68   Hanoi   Fail     Adult
8    9   Student_9   21          76   Hanoi   Pass     Young
12  13  Student_13   20          84   Hanoi   Pass     Young
15  16  Student_16   18          90  Cantho   Pass      Teen

Chủ đề 9 – Merge / Join DataFrame

Tạo DataFrame điểm tiếng Anh:

In [42]:
df_eng = pd.DataFrame({
    "id": [1, 2, 3, 4, 5],
    "english_score": [70, 88, 92, 65, 80]
})


Ví dụ 1: merge theo id (inner join)

In [43]:
df_merged = pd.merge(df, df_eng, on="id", how="inner")
df_merged.head()


id       name  age  math_score    city result age_group  english_score
0   1  Student_1   18          60   Hanoi   Fail      Teen             70
1   2  Student_2   19          62     HCM   Fail      Teen             88
2   3  Student_3   20          64  Danang   Fail     Young             92
3   4  Student_4   21          66  Cantho   Fail     Young             65
4   5  Student_5   22          68   Hanoi   Fail     Adult             80

Ví dụ 2: left join (giữ toàn bộ list học sinh)

In [52]:
df_left = pd.merge(df, df_eng, on="id", how="left")
df_left.head(20)


id        name  age  math_score    city result age_group  english_score
0    1   Student_1   18          60   Hanoi   Fail      Teen           70.0
1    2   Student_2   19          62     HCM   Fail      Teen           88.0
2    3   Student_3   20          64  Danang   Fail     Young           92.0
3    4   Student_4   21          66  Cantho   Fail     Young           65.0
4    5   Student_5   22          68   Hanoi   Fail     Adult           80.0
5    6   Student_6   18          70     HCM   Fail      Teen            NaN
6    7   Student_7   19          72  Danang   Fail      Teen            NaN
7    8   Student_8   20          74  Cantho   Fail     Young            NaN
8    9   Student_9   21          76   Hanoi   Pass     Young            NaN
9   10  Student_10   22          78     HCM   Pass     Adult            NaN
10  11  Student_11   18          80  Danang   Pass      Teen            NaN
11  12  Student_12   19          82  Cantho   Pass      Teen            NaN
12  13  Student_13   20          84   Hanoi   Pass     Young            NaN
13  14  Student_14   21          86     HCM   Pass     Young            NaN
14  15  Student_15   22          88  Danang   Pass     Adult            NaN
15  16  Student_16   18          90  Cantho   Pass      Teen            NaN
16  17  Student_17   19          92   Hanoi   Pass      Teen            NaN
17  18  Student_18   20          94     HCM   Pass     Young            NaN
18  19  Student_19   21          96  Danang   Pass     Young            NaN
19  20  Student_20   22          98  Cantho   Pass     Adult            NaN

Chủ đề 10 – Pivot table đơn giản

Ví dụ 1: Pivot – điểm toán trung bình theo city & nhóm tuổi

In [53]:
pivot1 = df.pivot_table(
    values="math_score",
    index="city",
    columns="age_group",
    aggfunc="mean"
)
pivot1


age_group  Adult  Teen  Young
city                         
Cantho      98.0  86.0   70.0
Danang      88.0  76.0   80.0
HCM         78.0  66.0   90.0
Hanoi       68.0  76.0   80.0

Ví dụ 2: Đếm số học sinh theo city & result



In [54]:
pivot2 = df.pivot_table(
    values="id",
    index="city",
    columns="result",
    aggfunc="count",
    fill_value=0
)
pivot2


result  Fail  Pass
city              
Cantho     2     3
Danang     2     3
HCM        2     3
Hanoi      2     3

4. 10 chủ đề nhỏ với NumPy (mỗi chủ đề 2 ví dụ)

In [ ]:
# import thư viện

In [58]:
import numpy as np
import pandas as pd

Đọc dữ liệu

In [59]:

df = pd.read_csv("students.csv")   # hoặc students.xlsx
df.head()


id       name  age  math_score    city
0   1  Student_1   18          60   Hanoi
1   2  Student_2   19          62     HCM
2   3  Student_3   20          64  Danang
3   4  Student_4   21          66  Cantho
4   5  Student_5   22          68   Hanoi

In [60]:
ages = df["age"].to_numpy()
math_scores = df["math_score"].to_numpy()


🎯 CHỦ ĐỀ 1 – Chuyển DataFrame → NumPy & xem thông tin

Ví dụ 1: Lấy mảng điểm toán

In [61]:
math_scores = df["math_score"].to_numpy()
print(math_scores)
print(math_scores.dtype, math_scores.shape)


[60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98]
int64 (20,)


Ví dụ 2: Lấy toàn bộ numeric columns

In [62]:
numeric_df = df[["age", "math_score"]]
numeric_matrix = numeric_df.to_numpy()
print(numeric_matrix)
print(numeric_matrix.shape)



[[18 60]
 [19 62]
 [20 64]
 [21 66]
 [22 68]
 [18 70]
 [19 72]
 [20 74]
 [21 76]
 [22 78]
 [18 80]
 [19 82]
 [20 84]
 [21 86]
 [22 88]
 [18 90]
 [19 92]
 [20 94]
 [21 96]
 [22 98]]
(20, 2)


CHỦ ĐỀ 2 – Thống kê cơ bản với NumPy

Ví dụ 1: Tính mean, median, std điểm toán

In [63]:
print("Mean:", math_scores.mean())
print("Median:", np.median(math_scores))
print("Std:", math_scores.std())



Mean: 79.0
Median: 79.0
Std: 11.532562594670797


Ví dụ 2: Tìm min / max và vị trí của nó

In [64]:
print("Min score:", math_scores.min())
print("Max score:", math_scores.max())
print("Index of max:", math_scores.argmax())


Min score: 60
Max score: 98
Index of max: 19


CHỦ ĐỀ 3 – Chuẩn hóa dữ liệu (Normalization)

Ví dụ 1: Min-Max Scaling

In [65]:
min_val = math_scores.min()
max_val = math_scores.max()
scaled = (math_scores - min_val) / (max_val - min_val)
print(scaled)


[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


Ví dụ 2: Scaling với Z-Score

In [ ]:
z = (math_scores - math_scores.mean()) / math_scores.std()
print(z)


CHỦ ĐỀ 4 – Broadcasting

(cho phép thực hiện các phép toán trên mảng có hình dạng khác nhau)

Ví dụ 1: Cộng toàn bộ điểm toán thêm 5

In [66]:
bonus = math_scores + 5
print(bonus)


[ 65  67  69  71  73  75  77  79  81  83  85  87  89  91  93  95  97  99
 101 103]


Ví dụ 2: Trừ tuổi mỗi bạn đi tuổi trung bình

In [67]:
age_centered = ages - ages.mean()
print(age_centered)


[-2. -1.  0.  1.  2. -2. -1.  0.  1.  2. -2. -1.  0.  1.  2. -2. -1.  0.
  1.  2.]


CHỦ ĐỀ 5 – Boolean Mask

Ví dụ 1: Lọc điểm > 80

In [73]:
boolean_mask = df["math_score"] > 80
filtered_data = df[boolean_mask]
print(filtered_data)


    id        name  age  math_score    city
11  12  Student_12   19          82  Cantho
12  13  Student_13   20          84   Hanoi
13  14  Student_14   21          86     HCM
14  15  Student_15   22          88  Danang
15  16  Student_16   18          90  Cantho
16  17  Student_17   19          92   Hanoi
17  18  Student_18   20          94     HCM
18  19  Student_19   21          96  Danang
19  20  Student_20   22          98  Cantho


Ví dụ 2: Lấy tuổi của học sinh ở HCM (kết hợp DF → NP)

In [74]:
mask = df["city"] == "HCM"
ages_hcm = ages[mask.to_numpy()]
print(ages_hcm)

[19 18 22 21 20]


CHỦ ĐỀ 6 – Xử lý missing value bằng NumPy

Giả lập trường hợp bị NaN

In [75]:
scores_nan = math_scores.astype("float")
scores_nan[3] = np.nan
scores_nan[7] = np.nan


Vd1: Tìm vị trí bị Null

In [76]:
nan_index = np.where(np.isnan(scores_nan))
print(nan_index)

(array([3, 7]),)


Ví dụ 2: Điền giá trị trung bình vào vị trí bị null

In [77]:
mean_val = np.nanmean(scores_nan)
scores_filled = np.where(np.isnan(scores_nan), mean_val, scores_nan)
print(scores_filled)

[60. 62. 64. 80. 68. 70. 72. 80. 76. 78. 80. 82. 84. 86. 88. 90. 92. 94.
 96. 98.]


CHỦ ĐỀ 7 – Reshape

Ví dụ 1: Chuyển điểm toán thành ma trận 4×5

In [78]:
mat = math_scores.reshape(4, 5)
print(mat)

[[60 62 64 66 68]
 [70 72 74 76 78]
 [80 82 84 86 88]
 [90 92 94 96 98]]


Ví dụ 2: Flatten ngược trở lại (flatten ngược thành 1x1)

In [79]:
mat_flat = mat.flatten()
print(mat_flat)

[60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98]


CHỦ ĐỀ 8 – Random với dữ liệu thật

Ví dụ 1: Lấy ngẫu nhiên 5 học sinh

In [88]:
idx = np.random.choice(len(df), 5, replace=False)
random_students = df.iloc[idx]
print(random_students)


    id        name  age  math_score    city
12  13  Student_13   20          84   Hanoi
7    8   Student_8   20          74  Cantho
19  20  Student_20   22          98  Cantho
4    5   Student_5   22          68   Hanoi
8    9   Student_9   21          76   Hanoi


Ví dụ 2: Tạo độ nhiễu (noise) cho điểm toán (mô phỏng 1 dữ liệu không hoàn hảo)

In [98]:
noise = np.random.randint(-3, 4, size=len(math_scores))
noisy_scores = math_scores + noise
print(noisy_scores)


[63 64 63 67 68 67 73 76 77 76 79 80 82 87 91 87 94 95 93 95]


CHỦ ĐỀ 9 – Tính correlation (tương quan)

Ví dụ 1: Tương quan giữa age và math_score

In [99]:
corr = np.corrcoef(ages, math_scores)
print(corr)


[[1.         0.24525574]
 [0.24525574 1.        ]]


Ví dụ 2: Tương quan nhiều cột

In [100]:
features = df[["age", "math_score"]].to_numpy().T
corr_all = np.corrcoef(features)
print(corr_all)


[[1.         0.24525574]
 [0.24525574 1.        ]]


CHỦ ĐỀ 10 – Vectorized operations nâng cao

Ví dụ 1: Chuẩn hóa toàn bộ numeric matrix (ages + math_score)

In [101]:
X = df[["age", "math_score"]].to_numpy()

X_norm = (X - X.mean(axis=0)) / X.std(axis=0)
print(X_norm)


[[-1.41421356 -1.64750894]
 [-0.70710678 -1.47408695]
 [ 0.         -1.30066495]
 [ 0.70710678 -1.12724296]
 [ 1.41421356 -0.95382097]
 [-1.41421356 -0.78039897]
 [-0.70710678 -0.60697698]
 [ 0.         -0.43355498]
 [ 0.70710678 -0.26013299]
 [ 1.41421356 -0.086711  ]
 [-1.41421356  0.086711  ]
 [-0.70710678  0.26013299]
 [ 0.          0.43355498]
 [ 0.70710678  0.60697698]
 [ 1.41421356  0.78039897]
 [-1.41421356  0.95382097]
 [-0.70710678  1.12724296]
 [ 0.          1.30066495]
 [ 0.70710678  1.47408695]
 [ 1.41421356  1.64750894]]


Ví dụ 2: Tính khoảng cách Euclidean giữa 2 học sinh

In [102]:
v1 = X[0]
v2 = X[1]
dist = np.linalg.norm(v1 - v2)
print(dist)


2.23606797749979
